In [2]:
import numpy as np

In [16]:
A = np.array([[2, 5],[8, 1]], dtype=np.dtype(float))
print(A)

[[2. 5.]
 [8. 1.]]


In [17]:
b = np.array([46,32], dtype=np.dtype(float)).reshape(2, 1)
print(b)

[[46.]
 [32.]]


In [20]:
M = np.hstack((A,b))
print(M)

[[ 2.  5. 46.]
 [ 8.  1. 32.]]


In [21]:
M[0,:]=M[0,:]/2
M[1,:]=M[1,:]/8
print(M)

[[ 1.     2.5   23.   ]
 [ 1.     0.125  4.   ]]


In [22]:
M[1,:]=M[1,:]-M[0,:]
print(M)

[[  1.      2.5    23.   ]
 [  0.     -2.375 -19.   ]]


In [23]:
x_2=-19./-2.375
print(x_2)

8.0


In [24]:
x_1=23.-2.5*8.0
print(x_1)

3.0


In [25]:
np.linalg.solve(A,b)

array([[3.],
       [8.]])

In [26]:
A = np.array([[1, 1],[-6, 2]], dtype=np.dtype(float))
print(A)

[[ 1.  1.]
 [-6.  2.]]


In [27]:
b = np.array([4,16], dtype=np.dtype(float)).reshape(2, 1)
print(b)

[[ 4.]
 [16.]]


In [28]:
M = np.hstack((A,b))
print(M)

[[ 1.  1.  4.]
 [-6.  2. 16.]]


In [29]:
M[0,:]=M[0,:]/1
M[1,:]=M[1,:]/(-6)
print(M)

[[ 1.          1.          4.        ]
 [ 1.         -0.33333333 -2.66666667]]


In [30]:
M[1,:]=M[1,:]-M[0,:]
print(M)

[[ 1.          1.          4.        ]
 [ 0.         -1.33333333 -6.66666667]]


In [31]:
M[1,2]/M[1,1]

5.0

In [32]:
A = np.array([[4, -3],[7, -8]], dtype=np.dtype(float))
print(A)

[[ 4. -3.]
 [ 7. -8.]]


In [34]:
A[0,0]*A[1,1]-A[0,1]*A[1,0]

-11.0

In [35]:
np.linalg.det(A)

-10.999999999999996

In [36]:
A = np.array([[-3,8,1],[2,2,-1],[-5,6,2]], dtype=np.dtype(float))
print(A)

[[-3.  8.  1.]
 [ 2.  2. -1.]
 [-5.  6.  2.]]


In [37]:
np.linalg.det(A)

-5.495603971894542e-15

In [48]:
M=np.array([[1,1,1,10000],[2,3,4,26000],[1,-2,0,0]], dtype=np.dtype(float))
print(M)

[[ 1.0e+00  1.0e+00  1.0e+00  1.0e+04]
 [ 2.0e+00  3.0e+00  4.0e+00  2.6e+04]
 [ 1.0e+00 -2.0e+00  0.0e+00  0.0e+00]]


In [49]:
M[1,:]=M[1,:]/2
print(M)

[[ 1.0e+00  1.0e+00  1.0e+00  1.0e+04]
 [ 1.0e+00  1.5e+00  2.0e+00  1.3e+04]
 [ 1.0e+00 -2.0e+00  0.0e+00  0.0e+00]]


In [50]:
M[1,:]=M[1,:]-M[0,:]
M[2,:]=M[2,:]-M[0,:]
print(M)

[[ 1.e+00  1.e+00  1.e+00  1.e+04]
 [ 0.e+00  5.e-01  1.e+00  3.e+03]
 [ 0.e+00 -3.e+00 -1.e+00 -1.e+04]]


In [51]:
M[1,:]=M[1,:]/M[1,1]
M[2,:]=M[2,:]/M[2,1]
print(M)

[[ 1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+04]
 [ 0.00000000e+00  1.00000000e+00  2.00000000e+00  6.00000000e+03]
 [-0.00000000e+00  1.00000000e+00  3.33333333e-01  3.33333333e+03]]


In [52]:
M[2,:]=M[2,:]-M[1,:]
print(M)

[[ 1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+04]
 [ 0.00000000e+00  1.00000000e+00  2.00000000e+00  6.00000000e+03]
 [-0.00000000e+00  0.00000000e+00 -1.66666667e+00 -2.66666667e+03]]


In [53]:
M[2,3]/M[2,2]

1599.9999999999998

In [6]:
A=np.array([[7,5,3],[3,2,5],[1,2,1]], dtype=np.dtype(float))
np.linalg.det(A)

-34.00000000000001

In [7]:
b=np.array([120,70,20], dtype=np.dtype(float))

In [13]:
M=np.hstack((A,b.reshape(3,1)))
print(M)

[[  7.   5.   3. 120.]
 [  3.   2.   5.  70.]
 [  1.   2.   1.  20.]]


In [9]:
b.reshape((3,1)

array([[120.],
       [ 70.],
       [ 20.]])

In [14]:
M[0,:]=M[0,:]/7
M[1,:]=M[1,:]/3

In [15]:
M[1,:]=M[1,:]-M[0,:]
M[2,:]=M[2,:]-M[0,:]

In [16]:
print(M)

[[ 1.          0.71428571  0.42857143 17.14285714]
 [ 0.         -0.04761905  1.23809524  6.19047619]
 [ 0.          1.28571429  0.57142857  2.85714286]]


In [18]:
M[1,:]=M[1,:]/M[1,1]
M[2,:]=M[2,:]/M[2,1]
print(M)

[[   1.            0.71428571    0.42857143   17.14285714]
 [  -0.            1.          -26.         -130.        ]
 [   0.            1.            0.44444444    2.22222222]]


In [19]:
M[2,:]=M[2,:]-M[1,:]
print(M)

[[   1.            0.71428571    0.42857143   17.14285714]
 [  -0.            1.          -26.         -130.        ]
 [   0.            0.           26.44444444  132.22222222]]


In [20]:
M[2,:]=M[2,:]/M[2,2]

In [21]:
M

array([[   1.        ,    0.71428571,    0.42857143,   17.14285714],
       [  -0.        ,    1.        ,  -26.        , -130.        ],
       [   0.        ,    0.        ,    1.        ,    5.        ]])

In [22]:
M[1,:]=M[1,:]+M[2,:]*26
print(M)

[[1.00000000e+00 7.14285714e-01 4.28571429e-01 1.71428571e+01]
 [0.00000000e+00 1.00000000e+00 2.84217094e-14 1.42108547e-13]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 5.00000000e+00]]


In [23]:
M[1,:]=M[1,:]/M[1,2]

In [24]:
M

array([[1.00000000e+00, 7.14285714e-01, 4.28571429e-01, 1.71428571e+01],
       [0.00000000e+00, 3.51843721e+13, 1.00000000e+00, 5.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 5.00000000e+00]])

In [25]:
np.linalg.solve(A,b)

array([15.,  0.,  5.])